fix(conditions): verify conditions fix, overriding fail steps
centralnicgroup-opensource/rtldev-middleware-semantic-release-whmcs pull request #151
Opened 2022-12-22 11:17 UTC by AsifNawaz-cnic

2023-01-02 10:29 UTC, KaiSchwarz-cnic requested changes

2023-01-02 10:29 UTC, KaiSchwarz-cnic commented on lib/verify.js
> +  if (cfg.ghtoken) {
I expect this line to be wrong, right?

`if (cfg.ghtoken) {` ---> `if (cfg.ghtoken === false) {`

2023-01-03 08:09 UTC, AsifNawaz-cnic commented on lib/verify.js
> +  if (cfg.ghtoken) {
Thanks for reporting it, seems like I forgot to add "! NOT" symbol 😃

2023-01-03 13:24 UTC, KaiSchwarz-cnic approved these changes
ty

2023-01-03 13:29 UTC, KaiSchwarz-cnic requested changes

2023-01-03 13:29 UTC, KaiSchwarz-cnic commented on package.json
> -  "name": "@hexonet/semantic-release-whmcs",
Please keep that name for now, even though it is hexonet-related. Otherwise we'll have to create a new organization space at npm which would of course be the right way but superfluous additional work for us.
(also: we would need to update other repositories that use that package to a different package name)

2023-01-03 13:46 UTC, AsifNawaz-cnic commented on package.json
> -  "name": "@hexonet/semantic-release-whmcs",
Okay noted, will make the changes shortly, ty.

2023-01-04 07:37 UTC, merged

2023-01-04 08:52 UTC, KaiSchwarz-cnic commented
:tada: This PR is included in version 4.0.4 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@hexonet/semantic-release-whmcs/v/4.0.4)
- [GitHub release](https://github.com/centralnicgroup-opensource/rtldev-middleware-semantic-release-whmcs/releases/tag/v4.0.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: